const DATA = {
  total: 32,
  items: {
    0: {
      day: 1.5,
      id: 4,
      military: undefined,
      civil: 'Адреналін',
      faggot: undefined,
      rusIsolation: false,
    },
    1: {
      day: 2.5,
      id: 3,
      military: 'Паніка',
      civil: undefined,
      faggot: undefined,
      rusIsolation: false,
    },
    2: {
      day: 3.5,
      id: 2,
      military: undefined,
      civil: 'Сумнів',
      faggot: undefined,
      rusIsolation: false,
    },
    3: {
      day: 4.5,
      id: 3,
      military: 'Самовпевненість',
      civil: undefined,
      faggot: 'Агонія',
      rusIsolation: false,
    },
    4: {
      day: 5.5,
      id: 2,
      military: undefined,
      civil: 'Апатія',
      faggot: 'Розгубленість',
      rusIsolation: false,
    },
    5: {
      day: 6.5,
      id: 5,
      military: ['легка ейфорія', 'жаль'],
      civil: 'Втома',
      faggot: undefined,
      rusIsolation: false,
    },
    6: {
      day: 7.5,
      id: 5,
      military: 'zero-point',
      civil: ['PLATO', 'Збудження'],
      faggot: undefined,
      rusIsolation: false,
    },
    7: {
      day: 8.5,
      id: 4,
      military: 'Стагнація',
      civil: 'Депресія',
      faggot: 'Розгубленість ',
      rusIsolation: false,
    },
    8: {
      day: 9.5,
      id: 4,
      military: undefined,
      civil: 'Розпач',
      faggot: 'Пеніафобія',
      rusIsolation: false,
    },
    9: {
      day: 10.5,
      id: 2,
      military: 'Відчай',
      civil: 'Рутина',
      faggot: undefined,
      rusIsolation: false,
    },
    10: {
      day: 11.5,
      id: 3,
      military: 'Тривога',
      civil: 'Втома',
      faggot: 'Повний терор',
      rusIsolation: false,
    },
    11: {
      day: 12.5,
      id: 4,
      military: undefined,
      civil: 'Атазагорафобiя',
      faggot: 'Манія переслідування',
      rusIsolation: false,
    },
    12: {
      day: 13.5,
      id: 5,
      military: 'Захват',
      civil: 'Втрата пильності',
      faggot: undefined,
      rusIsolation: false,
    },
    13: {
      day: 14.5,
      id: 5,
      military: 'Самотність',
      civil: 'Гнів',
      faggot: undefined,
      rusIsolation: false,
    },
    14: {
      day: 15.5,
      id: 6,
      military: 'Лють',
      civil: 'Байдужість',
      faggot: 'Паніка',
      rusIsolation: false,
    },
    15: {
      day: 16.5,
      id: 4,
      military: 'Спокій',
      civil: 'Провина',
      faggot: 'Безпорадність',
      rusIsolation: false,
    },
    16: {
      day: 17.5,
      id: 4,
      military: 'Деперсоналізація',
      civil: 'Синдром біженця',
      faggot: 'Ефект Аша',
      rusIsolation: false,
    },
    17: {
      day: 18.5,
      id: 4,
      military: undefined,
      civil: 'Прийняття',
      faggot: 'Синдром Зейгарнік',
      rusIsolation: false,
    },
    18: {
      day: 19.5,
      id: 4,
      military: 'Очікування',
      civil: 'Розчарування',
      faggot: undefined,
      rusIsolation: false,
    },
    19: {
      day: 20.5,
      id: 3,
      military: 'Спокій',
      civil: 'Провина вцілілого',
      faggot: 'Ефект Мілгрема',
      rusIsolation: false,
    },
    20: {
      day: 21.5,
      id: 4,
      military: 'Піднесення',
      civil: 'Деентузіазм',
      faggot: 'Сумнів',
      rusIsolation: false,
    },
    21: {
      day: 22.5,
      id: 3,
      military: 'Злість',
      civil: ['Персекуторна тривога', 'Відторгнення'],
      faggot: 'Параноя',
      rusIsolation: false,
    },
    22: {
      day: 23.5,
      id: 4,
      military: 'Фінішер',
      civil: 'Переклад провини',
      faggot: 'Меншовартість',
      rusIsolation: false,
    },
    23: {
      day: 24.5,
      id: 5,
      military: 'Спостереження',
      civil: 'Пошук',
      faggot: 'Демонізація',
      rusIsolation: false,
    },
    24: {
      day: 25.5,
      id: 5,
      military: 'Самовпевненість',
      civil: 'Виснаження',
      faggot: 'Героїзація ворога',
      rusIsolation: false,
    },
    25: {
      day: 26.5,
      id: 4,
      military: 'Сум',
      civil: 'Синдром Дженовезе',
      faggot: 'Пошук слабких',
      rusIsolation: false,
    },
    26: {
      day: 27.5,
      id: 2,
      military: 'Апатія',
      civil: 'Дифузія відповідальності',
      faggot: 'Робота зі слабкими',
      rusIsolation: false,
    },
    27: {
      day: 28.5,
      id: 4,
      military: 'Полювання',
      civil: 'Ізоляція',
      faggot: 'Страх',
      rusIsolation: false,
    },
    28: {
      day: 29.5,
      id: 4,
      military: 'Засідка',
      civil: 'Локальна напруга',
      faggot: 'Виправдання',
      rusIsolation: false,
    },
    29: {
      day: 30.5,
      id: 4,
      military: 'Овації',
      civil: 'Абаліенція',
      faggot: 'Прийняття',
      rusIsolation: false,
    },
    30: {
      day: 31.5,
      id: 2,
      military: 'Слава Україні',
      civil: 'Героям Слава',
      faggot: 'Путін хуйло',
      rusIsolation: false,
    },
    31: {
      day: 32.5,
      id: 7,
      military: 'ібуть мамок хароших русских',
      civil: 'Васторг',
      faggot: 'Ахуй',
      rusIsolation: false,
    },
    32: {
      day: 33.5,
      id: 7,
      military: 'ібуть мамок хароших русских',
      civil: 'Васторг',
      faggot: 'Ахуй',
      rusIsolation: false,
    },
  },
};

export default DATA;
