const DATA = {
  total: 30,
  items: {
    0: {
      day: 1,
      id: 4,
      military: undefined,
      civil: 'Адреналін',
      faggot: undefined,
      rusIsolation: false,
    },
    1: {
      day: 2,
      id: 3,
      military: 'Паніка',
      civil: undefined,
      faggot: undefined,
      rusIsolation: false,
    },
    2: {
      day: 3,
      id: 2,
      military: undefined,
      civil: 'Сумнів',
      faggot: undefined,
      rusIsolation: false,
    },
    3: {
      day: 4,
      id: 3,
      military: 'Самовпевненість',
      civil: undefined,
      faggot: 'Агонія',
      rusIsolation: false,
    },
    4: {
      day: 5,
      id: 2,
      military: undefined,
      civil: 'Апатія',
      faggot: 'Розгубленість',
      rusIsolation: false,
    },
    5: {
      day: 6,
      id: 5,
      military: ['легка ейфорія', 'жаль'],
      civil: 'Втома',
      faggot: undefined,
      rusIsolation: false,
    },
    6: {
      day: 7,
      id: 5,
      military: 'zero-point',
      civil: ['PLATO', 'Збудження'],
      faggot: undefined,
      rusIsolation: false,
    },
    7: {
      day: 8,
      id: 4,
      military: 'Стагнація',
      civil: 'Депресія',
      faggot: 'Розгубленість ',
      rusIsolation: false,
    },
    8: {
      day: 9,
      id: 4,
      military: undefined,
      civil: 'Розпач',
      faggot: 'Пеніафобія',
      rusIsolation: false,
    },
    9: {
      day: 10,
      id: 2,
      military: 'Відчай',
      civil: 'Рутина',
      faggot: undefined,
      rusIsolation: false,
    },
    10: {
      day: 11,
      id: 3,
      military: 'Тривога',
      civil: 'Втома',
      faggot: 'Повний терор',
      rusIsolation: false,
    },
    11: {
      day: 12,
      id: 4,
      military: undefined,
      civil: 'Атазагорафобiя',
      faggot: 'Манія переслідування',
      rusIsolation: false,
    },
    12: {
      day: 13,
      id: 5,
      military: 'Захват',
      civil: 'Втрата пильності',
      faggot: undefined,
      rusIsolation: false,
    },
    13: {
      day: 14,
      id: 5,
      military: 'Самотність',
      civil: 'Гнів',
      faggot: undefined,
      rusIsolation: false,
    },
    14: {
      day: 15,
      id: 6,
      military: 'Лють',
      civil: 'Байдужість',
      faggot: 'Паніка',
      rusIsolation: false,
    },
    15: {
      day: 16,
      id: 4,
      military: 'Спокій',
      civil: 'Провина',
      faggot: 'Безпорадність',
      rusIsolation: false,
    },
    16: {
      day: 17,
      id: 4,
      military: 'Деперсоналізація',
      civil: 'Синдром біженця',
      faggot: 'Ефект Аша',
      rusIsolation: false,
    },
    17: {
      day: 18,
      id: 4,
      military: undefined,
      civil: 'Прийняття',
      faggot: 'Синдром Зейгарнік',
      rusIsolation: false,
    },
    18: {
      day: 19,
      id: 4,
      military: 'Очікування',
      civil: 'Розчарування',
      faggot: undefined,
      rusIsolation: false,
    },
    19: {
      day: 20,
      id: 3,
      military: 'Спокій',
      civil: 'Провина вцілілого',
      faggot: 'Ефект Мілгрема',
      rusIsolation: false,
    },
    20: {
      day: 21,
      id: 4,
      military: 'Піднесення',
      civil: 'Деентузіазм',
      faggot: 'Сумнів',
      rusIsolation: false,
    },
    21: {
      day: 22,
      id: 3,
      military: 'Злість',
      civil: 'Відторгнення',
      faggot: 'Параноя',
      rusIsolation: false,
    },
    22: {
      day: 23,
      id: 4,
      military: 'Фінішер',
      civil: 'Переклад провини',
      faggot: 'Меншовартість',
      rusIsolation: false,
    },
    23: {
      day: 24,
      id: 5,
      military: 'Спостереження',
      civil: 'Пошук',
      faggot: 'Демонізація',
      rusIsolation: false,
    },
    24: {
      day: 25,
      id: 5,
      military: 'Самовпевненість',
      civil: 'Виснаження',
      faggot: 'Героїзація ворога',
      rusIsolation: false,
    },
    25: {
      day: 26,
      id: 4,
      military: 'Сум',
      civil: 'Синдром Дженовезе',
      faggot: 'Пошук слабких',
      rusIsolation: false,
    },
    26: {
      day: 27,
      id: 2,
      military: 'Апатія',
      civil: 'Дифузія відповідальності',
      faggot: 'Робота зі слабкими',
      rusIsolation: false,
    },
    27: {
      day: 28,
      id: 4,
      military: 'Полювання',
      civil: 'Ізоляція',
      faggot: 'Страх',
      rusIsolation: false,
    },
    28: {
      day: 29,
      id: 4,
      military: 'Засідка',
      civil: 'Локальна напруга',
      faggot: 'Виправдання',
      rusIsolation: false,
    },
    29: {
      day: 30,
      id: 4,
      military: 'Овації',
      civil: 'Абаліенція',
      faggot: 'Прийняття',
      rusIsolation: false,
    },

  },
};

export default DATA;
